Microservices/Construction/Django- Web Framework/details/exercise3/urls.py
from django.contrib import admin
from django.conf.urls import include,url


urlpatterns = [
    url(r'^webpoll/',include('webpoll.urls')),
    url(r'^admin/', admin.site.urls),
]

Microservices/Construction/Django- Web Framework/details/webpoll/urls.py
from django.conf.urls import url,include
from . import views

app_name='webpoll'
urlpatterns=[
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^(?P<pk>[0-9]+)/$',views.QuestionDetailView.as_view(),name='detail'),
    ]

Microservices/Construction/Django- Web Framework/details/webpoll/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class question(models.Model):
    questionname = models.CharField(max_length=200)
    pubdate = models.DateTimeField("Published Date")

    def __str__(self):
        return self.questionname
    
    def is_recent(self):
        now=timezone.now()
        return now - datetime.timedelta(days=1) <= self.pubdate <= now
    
class choice(models.Model):
    choicename = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)
    quest = models.ForeignKey(question, on_delete = models.CASCADE)

    def __Str__(Self):
        return self.choicename

Microservices/Construction/Django- Web Framework/details/webpoll/views.py
from django.views import generic
from django.utils import timezone
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse

from .models import question,choice

class HomeView(generic.ListView):
    template_name='webpoll/home.html'
    context_object_name='recent_question_list'
    def get_queryset(self):
        return question.objects.filter(pubdate__lte=timezone.now()).order_by('-pubdate')[:6]

class QuestionDetailView(generic.DetailView):
    model=question
    template_name='webpoll/question_detail.html'
    def get_queryset(self):
        return question.objects.filter(pubdate__lte=timezone.now())

Microservices/Construction/Django- Web Framework/details/webpoll/templates/webpoll/home.html
<!DOCTYPE html>
{% if recent_question_list %}
    <ul>
    {% for question in recent_question_list %}
        <li><a href="{% url 'webpoll:detail' question.id %}">{{ question.questionname }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Questions not available for polling!</p>
{% endif %}

Microservices/Construction/Django- Web Framework/details/webpoll/templates/webpoll/question_detail.html
<!DOCTYPE html>

<h2>{{ question.questionname }}</h2>

<form>

{% for choice in question.choice_set.all %}
{% endfor %}
<input type="submit" value="Submit Vote" />
</form>