Microservices/Construction/Django- Web Framework/test-views/exercise7/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url(r'^webpoll/', include('webpoll.urls')),
    url(r'^admin/', admin.site.urls),
]

Microservices/Construction/Django- Web Framework/test-views/webpoll/urls.py
from django.conf.urls import url,include
from . import views

app_name='webpoll'
urlpatterns=[
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^(?P<pk>[0-9]+)/$',views.QuestionDetailView.as_view(),name='detail'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<pk>[0-9]+)/result/$',views.VoteResultView.as_view(),name='result'),
    ]

Microservices/Construction/Django- Web Framework/test-views/webpoll/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class question(models.Model):
    questionname = models.CharField(max_length=200)
    pubdate = models.DateTimeField("Published Date")

    def __str__(self):
        return self.questionname
    
    def is_recent(self):
        now=timezone.now()
        return now - datetime.timedelta(days=1) <= self.pubdate <= now
    
class choice(models.Model):
    choicename = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)
    quest = models.ForeignKey(question, on_delete = models.CASCADE)

    def __Str__(Self):
        return self.choicename

Microservices/Construction/Django- Web Framework/test-views/webpoll/views.py
from django.views import generic
from django.utils import timezone
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import question,choice

# Create your views here.
class HomeView(generic.ListView):
    template_name='webpoll/home.html'
    context_object_name='recent_question_list'
    def get_queryset(self):
        # return the recent 6 published questions
        return question.objects.filter(pubdate__lte=timezone.now()).order_by('-pubdate')[:6]

class QuestionDetailView(generic.DetailView):
    model=question
    template_name='webpoll/question_detail.html'
    def get_queryset(self):
        return question.objects.filter(pubdate__lte=timezone.now())

def vote(request, question_id):
    quest=get_object_or_404(question,pk=question_id)
    try:
        selected_choice = quest.choice_set.get(pk=request.POST['choice'])
    
    except (KeyError, choice.DoesNotExist):
        return render(request, 'webpoll/question_detail.html', {
            'question':quest,
            'error_message':"You didn't select a choice",
            })
    else:
        selected_choice.vote+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('webpoll:result',args=(question_id,)))
    
class VoteResultView(generic.DetailView):
    model=question
    template_name='webpoll/vote_result.html'

Microservices/Construction/Django- Web Framework/test-views/webpoll/templates/webpoll/home.html
<!DOCTYPE html>
{% if recent_question_list %}
    <ul>
    {% for question in recent_question_list %}
        <li><a href="{% url 'webpoll:detail' question.id %}">{{ question.questionname }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Questions not available for polling!</p>
{% endif %}

Microservices/Construction/Django- Web Framework/test-views/webpoll/templates/webpoll/question_detail.html
<!DOCTYPE html>

<h2>{{ question.questionname }}</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'webpoll:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choicename }}</label><br />
{% endfor %}
<input type="submit" value="Submit Vote" />
</form>

Microservices/Construction/Django- Web Framework/test-views/webpoll/templates/webpoll/vote_result.html
<!DOCTYPE html>

<h2>{{ question.questionname }}</h2>
<ul>
{% for choice in question.choice_set.all %}
    <li>
    {{ choice.choicename }} -- {{ choice.vote }} vote{{ choice.vote|pluralize }}
    </li> 
{% endfor %}
</ul>

<a href="{% url 'webpoll:detail' question.id %}"> Vote Again? </a>